### PR TITLE
allows the user to specify a working dir for startup

### LINKED ISSUE #13: Project root is not necessarily the right working dir to run psci
This is more of an observation than an issue, I suppose.

I spent quite a lot of time trying to get `psci-mode` to work with the [purescript book examples](https://github.com/paf31/purescript-book). I ran into two issues:
- The examples are in a 'mono-repo', ie each chapter has its own purescript project in a repo subdir. [`projectile-project-root`](https://github.com/ardumont/emacs-psci/blob/master/psci.el#L83) returns the root of the git project, but in this case it's the wrong directory to run `psci` in.
- The error message from `psci` and `psci-mode` was the usual: `PSCi requires the purescript-psci-support package to be installed.`, which is very frustrating when you know that the package is installed already.

I'd suggest that `psci-mode` would try to work out the project root with eg looking for a `bower.json` file or a `bower_components` directory, but I'm new to purescript, so I'm not 100% confident this is universally appropriate.

And it would be super helpful towards newcomers if it was possible to render an error message that included some more hints about how to fix the issue.

Thanks for a great mode!

### LINKED ISSUE #20: M-x psci fails
Please forgive whatever I'm missing, it's my first day with Purescript.  When I run `M-x psci`the repl fails to load and I get an Emacs error:
`psci/--project-root!: Wrong type argument: stringp, nil`

If I run `pulp repl` from a command line everything works fine.

I also see a previous issue #3 but that doesn't seem relevant since my searches suggest `.psci` files are no longer used.  The entirety of my psci-related configuration is, as suggested:

`(add-hook 'purescript-mode-hook 'inferior-psci-mode)`

### PR DESCRIPTION
**Pull request by kRITZCREEK**
This is the same as how we do it in psc-ide-emacs

FIxes #13 Fixes #20

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@karljs Could you check if this fixes your issue?

**Comment by karljs** [comment]
@kRITZCREEK Thanks for the quick solution.  This does indeed fix my problem.  I didn't realize the working directory was not shared between the Emacs psc-ide and psci packages.  Feel free to close my issue.

**Comment by kRITZCREEK** [comment]
Thanks for confirming!

**Comment by vyorkin** [comment]
just noticed one small issue with [repl-toggle mentioned in README](https://github.com/purescript-emacs/emacs-psci#repl-toggle) + emacs-psci – I have to pass `psci/--project-root!` to `psci` function like this:
```
(add-to-list 'rtog/mode-repl-alist '(purescript-mode . (lambda () (psci (psci/--project-root!)))))
```

**Comment by kRITZCREEK** [comment]
Huh, I didn't know about that one. Do you think you could put a PR together that fixes it in this package?

**Comment by vyorkin** [comment]
ok, `psci/--project-root!` is not enough, it doesn't switch back to the source buffer after switching to repl with `rtog/toggle-repl` and I have no idea why & how to fix it, sorry

**Comment by kRITZCREEK** [comment]
Okay, thanks for reporting anyway, I don't really use that functionality, so if it's broken we could either take it out or wait a little longer and see if someone wants to fix it.

**Pull request merged**
